#!/usr/bin/env bash
# a scipt that displays the content of the file /etc/passwd
# the script displays only username, userid, home directory

# read the file /etc/passwd using the read command
#!/usr/bin/bash 
i=0;
while [ $i -le 0 ]; do
    cut -d : -f 1,3,6 < /etc/passwd
    ((i++))
done 