#!/usr/bin/env bash
# script that extracts uname, pswd u_id, GID, home_directory and shell_directory, from /etc/passwd

while IFS=: read -r uname pswd u_id g_id uid_info home_directory shell_directory; do
    # printf("The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s", $uname, $g_id, $home_direcory, $shell_directory, $u_id, $pswd, $uid_info)
    echo "The user $uname is part of the $g_id gang, lives in $home_directory and rides $shell_directory. $u_id's place is protected by the passcode $pswd, more info about the user here: $uid_info"
  
done < /etc/passwd