#!/usr/bin/env bash
# print 'bad luck' at 4th loop, 'good luck' at 8th loop and 'Best School' for the other
i=1
while [ $i -lt 11 ]; do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done