#!/usr/bin/env bash
# a script that displays numbers from 1 to 20 and displays 'bad luck from China' for the fifth loop, 'bad luck from Japan' for the 10th loop and 'bad luck from Italy' for the 18th loop'
i=1
while [ $i -le 20 ]; do
    case $i in
        5 )
            echo "bad luck from China" ;;
            
        10 )
            echo "bad luck from Japan" ;;
        18 )
            echo "bad luck from Italy" ;;
        * )
            echo $i ;;
        esac
	((i++))
done
