#!/usr/bin/env bash
# script that prints information about school file
# check if the 'school' file exists

if [ -e school ]
then
    echo "school file exists"
    # check if file is empty
    if [ -s school ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    # check if file is a regular file
    if [ -f school ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi